services:
  postgres:
    container_name: elearning-db
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: elearning
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
#  api:
#    image: thuanvn2002/elearning-be:latest
#    ports:
#      - "8082:8082"
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
#    networks:
#      - postgres
#    depends_on:
#      - postgres
#  ui:
#    image: thuanvn2002/elearning-fe:latest
#    ports:
#      - "80:80"
#    networks:
#      - postgres
#    restart: unless-stopped
networks:
  postgres:
    driver: bridge

volumes:
  db_data:


