services:
  postgres:
    container_name: elearning-postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: elearning
    volumes:
      - elearning_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: elearning-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  # api:
  #   container_name: elearning-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: thuanvn2002/elearning-api
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=prod
  #   networks:
  #     - postgres
  #   depends_on:
  #     - postgres
networks:
  postgres:
    driver: bridge

volumes:
  elearning_data:
  pgadmin:

    #   ui:
    #     container_name: elearning-ui
    #     build:
    #       context: ./elearning_ui
    #       dockerfile: Dockerfile
    #     image: thuanvn2002/elearning-ui
    #     ports:
    #       - "5173:5173"
    #     networks:
    #       - postgres
